### PR TITLE
Considering array in query strings by checkboxes

### PR DESCRIPTION
**Pull request by h-kusaba-1001**
I consider array in query strings.
For example, checkboxes, multiple selectbox, etc...

~* no test code~

### CODE REVIEW

**Review by toh-karashi — APPROVED** [review]
LGTM 👍

**Comment by h-kusaba-1001** [comment]
added test code for `Sortable\SortableLink::generateQuery()`
d264e953c4a6b4d899b1d582f432c7476c9b64f2...d3c7ec67395d2bf0d3d790132ae8200e475d476c

**Review by toh-karashi — APPROVED** [review]
LGTM

**Review by kozo — APPROVED** [review]
LGTM!!

**Pull request merged**
